### ISSUE TITLE
report bug

### ISSUE THREAD

**Issue by gouzhiyuan** [stormtea123/ConvertChineseCharacters#1]
sublime3 安装插件后 无法转换 
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "convertChineseCharactersFor3 in /Users/black/Library/Application Support/Sublime Text 3/Installed Packages/ConvertChineseCharacters.sublime-package", line 42, in run
  File "./python3.3/re.py", line 156, in match
TypeError: expected string or buffer

**Comment by stormtea123** [comment]
@gouzhiyuan 描述具体一点，文件类型？通过右键转换还是快捷窗口？文件发我看看

**Comment by gouzhiyuan** [comment]
回复这么快 感动~~
右键和快捷窗口都是一样的
文件类型 就是开了个新窗口  没保存成文件

**Comment by gouzhiyuan** [comment]
[test.txt](https://github.com/stormtea123/ConvertChineseCharacters/files/1090666/test.txt)
这是保存了之后的文件 报错变成不能解析的文件类型

**Comment by stormtea123** [comment]
仅支持 .js, .json, .css 文件类型

**Comment by gouzhiyuan** [comment]
恩 仔细看了一下介绍和代码 看明白了 感谢回复！
